#spring:
#  datasource:
#    url: "jdbc:mysql://localhost:3306/fingry"
#    username: "root"
#    password: "@Blessing22#"
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#
#server:
#  port: 8081
#
##Logging configuration
#logging:
#  file:
#    path: ./var/logs/
#  level:
#    root: WARN
#    org:
#      springframework:
#        security: WARN
#
#email: ogbuisreal@gmail.com
#host: smtp.gmail.com
#protocol: smtp
#password: "sowwtfafgaxlqund"
#port: 465