spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/fingry"
    username: "root"
    password: "@Blessing22#"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: "guest"
      password: "guest"

springdoc:
  swagger-ui:
    path: /index.html
    operationsSorter: method
    tagsSorter: alpha
    enabled: true
    default-models-expand-depth: -1
  paths-to-match: /api/**


# server configuration
server:
  port: 8081
  servlet:
    context-path: /fingryd
  tomcat:
    threads:
      max: 10
      min-spare: 5

#Logging configuration
logging:
  file:
    path: ./var/logs/
  level:
    root: WARN
    org:
      springframework:
        security: WARN

# Mail configuration
email: ogbuisreal22@gmail.com
host: smtp.gmail.com
protocol: smtp
password: sowwtfafgaxlqund
port: 465

# file Writer path
filename: "C:\\Users\\USER\\fingryd\\src\\main\\java\\com\\example\\fingryd\\logging\\customer_log.txt"

# Security configuration
SECRET_KEY: "5367566B59703373357638792F423F4528482B4D6251655468576D5A71347437"