spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/fingry"
    username: "root"
    password: "@Blessing22#"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: /swagger-ui/api-docs

server:
  port: 8081

#Logging configuration
logging:
  file:
    path: ./var/logs/
  level:
    root: WARN
    org:
      springframework:
        security: WARN

# Mail configuration
email: ogbuisreal22@gmail.com
host: smtp.gmail.com
protocol: smtp
password: sowwtfafgaxlqund
port: 465

# file Writer path
filename: "C:\\Users\\USER\\fingryd\\src\\main\\java\\com\\example\\fingryd\\logging\\customer_log.txt"

# Security configuration
SECRET_KEY: "5367566B59703373357638792F423F4528482B4D6251655468576D5A71347437"